project_pettycash/pettycash_app/urls.py
from django.urls import path
from . import views

app_name = 'pettycash_app'

urlpatterns = [
    #home
    path('', views.chooseCashBook, name='choose_cashbook'),

    #category
    path('category/', views.viewCategory, name='category'),
    path('create_category/', views.createCategory, name='create_category'),
    path('update_category/<uuid:id>/', views.updateCategory, name='update_category'),
    path('delete_category/<uuid:id>/', views.deleteCategory, name='delete_category'),
    
    #pettycash
    path('view_pettycash/', views.viewPettyCash, name='view_pettycash'),
    path('create_pettycash/', views.createPettyCash, name='create_pettycash'),
    path('update_pettycash/<uuid:id>/', views.updatePettyCash, name='update_pettycash'),
    path('each_pettycash/<uuid:id>/', views.eachPettyCash, name='each_pettycash'),
    path('delete_pettycash/<uuid:id>/', views.deletePettyCash, name='delete_pettycash'),
    path('petty_cash_signature/', views.pettyCashSignature, name='petty_cash_signature'),
    
    #federal pettycash
    path('view_federal_pettycash/', views.viewFederalPettyCash, name='view_federal_pettycash'),
    path('create_federal_pettycash/', views.createFederalPettyCash, name='create_federal_pettycash'),
    path('update_federal_pettycash/<uuid:id>/', views.updateFederalPettyCash, name='update_federal_pettycash'),
    path('each_federal_pettycash/<uuid:id>/', views.eachFederalPettyCash, name='each_federal_pettycash'),
    path('federal_bank_signature/', views.federalBankSignature, name='federal_bank_signature'),
    path('delete_federal_pettycash/<uuid:id>/', views.deleteFederalPettyCash, name='delete_federal_pettycash'),
    
    #sbi pettycash
    path('view_sbi_pettycash/', views.viewSBIPettyCash, name='view_sbi_pettycash'),
    path('create_sbi_pettycash/', views.createSBIPettyCash, name='create_sbi_pettycash'),
    path('update_sbi_pettycash/<uuid:id>/', views.updateSBIPettyCash, name='update_sbi_pettycash'),
    path('each_sbi_pettycash/<uuid:id>/', views.eachSBIPettyCash, name='each_sbi_pettycash'),
    path('sbi_bank_signature/', views.SbiBankSignature, name='sbi_bank_signature'),
    path('delete_sbi_pettycash/<uuid:id>/', views.deleteSBIPettyCash, name='delete_sbi_pettycash'),

    #fetching opening balance
    path('opening_balance/', views.fetchOpeningBalance, name='opening_balance'),
    path('federal_opening_balance/', views.fetchFederalOpeningBalance, name='federal_opening_balance'),
    path('sbi_opening_balance/', views.fetchSBIOpeningBalance, name='sbi_opening_balance'),
    
    #filtering
    path('filter_pettycash/', views.filter_pettycash, name='filter_pettycash'),
    path('filter_federal_pettycash/', views.filter_federal_pettycash, name='filter_federal_pettycash'),
    path('filter_sbi_pettycash/', views.filter_sbi_pettycash, name='filter_sbi_pettycash'),
    
    #opening Balance
    path('view_opening_balance/', views.viewOpeningBalance, name='view_opening_balance'),
    path('create_opening_balance/', views.createOpeningBalance, name='create_opening_balance'),
    path('update_opening_balance/<uuid:id>/', views.updateOpeningBalance, name='update_opening_balance'),
    path('delete_opening_balance/<uuid:id>/', views.deleteOpeningBalance, name='delete_opening_balance'),
    
    #excel file generating
    path('pettycash_balance_sheet_excel/', views.pettycash_balance_sheet_excel, name='pettycash_balance_sheet'),
    path('federal_balance_sheet_excel/', views.federal_balance_sheet_excel, name='federal_balance_sheet'),
    path('sbi_balance_sheet_excel/', views.sbi_balance_sheet_excel, name='sbi_balance_sheet'),
    
    #pdf file generating
    path('pettycash_all_pdf/', views.pettycash_all_pdf, name='pettycash_all_pdf'),
    path('pettycash_custom_pdf/', views.pettycash_custom_pdf, name='pettycash_custom_pdf'),
]

project_pettycash/project_pettycash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pettycash_app.urls')),
    path('auth/', include(urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_pettycash/pettycash_app/models.py
from django.db import models
import uuid
from django.utils.timezone import now as current_date

# Create your models here.
class Category(models.Model):
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    category = models.CharField(max_length=100)
    general_ledger_code = models.IntegerField(unique=True)
    
    def __str__(self):
        return self.category

class PettyCash(models.Model):
    
    CASH_FLOW = (
        ('Cash In', 'Cash In'),
        ('Cash Out', 'Cash Out'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    voucher_code = models.CharField(max_length=150, blank=True, unique=True)
    to_or_from = models.CharField(max_length=200)
    created_date = models.DateField(default=current_date)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cash_flow = models.CharField(max_length=50, choices=CASH_FLOW)
    amount = models.FloatField()
    description = models.CharField(max_length=1200)
    image = models.ImageField(blank=True, null=True, upload_to="voucher_signature/")
    
    def __str__(self):
        return self.voucher_code
    
class FederalBank(models.Model):
    
    CASH_FLOW = (
        ('Cash In', 'Cash In'),
        ('Cash Out', 'Cash Out'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    voucher_code = models.CharField(max_length=150, blank=True, unique=True)
    to_or_from = models.CharField(max_length=200)
    created_date = models.DateField(default=current_date)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cash_flow = models.CharField(max_length=50, choices=CASH_FLOW)
    amount = models.FloatField()
    description = models.CharField(max_length=1200)
    image = models.ImageField(blank=True, null=True, upload_to="voucher_signature/")
    
    def __str__(self):
        return self.voucher_code
    
class SBIBank(models.Model):
    
    CASH_FLOW = (
        ('Cash In', 'Cash In'),
        ('Cash Out', 'Cash Out'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    voucher_code = models.CharField(max_length=150, blank=True, unique=True)
    to_or_from = models.CharField(max_length=200)
    created_date = models.DateField(default=current_date)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cash_flow = models.CharField(max_length=50, choices=CASH_FLOW)
    amount = models.FloatField()
    description = models.CharField(max_length=1200)
    image = models.ImageField(blank=True, null=True, upload_to="voucher_signature/")
    
    def __str__(self):
        return self.voucher_code
    
class VoucherCodeStore(models.Model):
    
    voucher_code = models.CharField(max_length=200)
    
    def __str__(self):
        return self.voucher_code
    
class OpeningBalance(models.Model):
    
    TYPE = (
        ('PettyCash', 'PettyCash'),
        ('Federal Bank', 'Federal Bank'),
        ('SBI Bank', 'SBI Bank'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    opening_balance = models.DecimalField(max_digits=50, decimal_places=2)
    opening_balance_of = models.CharField(max_length=50, choices=TYPE)
    opening_date = models.DateField(null=True, blank=True)
    
    def __str__(self):
        return str(self.opening_date)

project_pettycash/pettycash_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from .forms import *
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from decimal import Decimal, ROUND_HALF_UP
from datetime import datetime
from PIL import Image
from django.core.files.base import ContentFile
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Spacer, Image, PageBreak, Frame, PageTemplate
import base64
from openpyxl import Workbook
from io import BytesIO
from openpyxl.utils import get_column_letter
from openpyxl.styles import Alignment



# First Page-----------------------------------------------------------------------------------------------------------------------------------------
@login_required
def chooseCashBook(request):
    return render(request, 'main.html')

# FetchClosingBalance--------------------------------------------------------------------------------------------------------------------------------
@login_required
def fetchOpeningBalance(request):
        
    try:
        op_balance = OpeningBalance.objects.filter(opening_balance_of="PettyCash").first()
        
        if op_balance:
            
            op_balance_amount = op_balance.opening_balance
            
            pettycashes = PettyCash.objects.all()
            
            pettycash_closing_balance = 0
            
            for pettycash in pettycashes:
                
                if pettycash.cash_flow == "Cash In":
                    pettycash_closing_balance = pettycash_closing_balance + pettycash.amount
                else:
                    pettycash_closing_balance = pettycash_closing_balance - pettycash.amount
                
            closing_balance = float(op_balance_amount) + pettycash_closing_balance
            
            closing_balance = Decimal(closing_balance).quantize(Decimal('0.00'), rounding=ROUND_HALF_UP)
            
            data = {'closing_balance': {
            'balance': closing_balance,
            }}
            
        else:
            
            data = {'closing_balance': {
            'balance': '0.00',
            }}
        
        return JsonResponse(data)
    except OpeningBalance.DoesNotExist:
        return JsonResponse({'error': 'Balance not found'}, status=404)

@login_required
def fetchFederalOpeningBalance(request):
        
    try:
        op_balance = OpeningBalance.objects.filter(opening_balance_of="Federal Bank").first()
        
        if op_balance:
            
            op_balance_amount = op_balance.opening_balance
            
            federal_pettycashes = FederalBank.objects.all()
            
            pettycash_closing_balance = 0
            
            for federal_pettycash in federal_pettycashes:
                
                if federal_pettycash.cash_flow == "Cash In":
                    pettycash_closing_balance = pettycash_closing_balance + federal_pettycash.amount
                else:
                    pettycash_closing_balance = pettycash_closing_balance - federal_pettycash.amount
                
            closing_balance = float(op_balance_amount) + pettycash_closing_balance
            
            closing_balance = Decimal(closing_balance).quantize(Decimal('0.00'), rounding=ROUND_HALF_UP)
            
            data = {'closing_balance': {
            'balance': closing_balance,
            }}
            
        else:
            
            data = {'closing_balance': {
            'balance': '0.00',
            }}
        
        return JsonResponse(data)
    except OpeningBalance.DoesNotExist:
        return JsonResponse({'error': 'Balance not found'}, status=404)

@login_required
def fetchSBIOpeningBalance(request):
        
    try:
        op_balance = OpeningBalance.objects.filter(opening_balance_of="SBI Bank").first()
        
        if op_balance:
            
            op_balance_amount = op_balance.opening_balance
            
            sbi_pettycashes = SBIBank.objects.all()
            
            pettycash_closing_balance = 0
            
            for sbi_pettycash in sbi_pettycashes:
                
                if sbi_pettycash.cash_flow == "Cash In":
                    pettycash_closing_balance = pettycash_closing_balance + sbi_pettycash.amount
                else:
                    pettycash_closing_balance = pettycash_closing_balance - sbi_pettycash.amount
                
            closing_balance = float(op_balance_amount) + pettycash_closing_balance
            
            closing_balance = Decimal(closing_balance).quantize(Decimal('0.00'), rounding=ROUND_HALF_UP)
            
            data = {'closing_balance': {
            'balance': closing_balance,
            }}
            
        else:
            
            data = {'closing_balance': {
            'balance': '0.00',
            }}
        
        return JsonResponse(data)
    except OpeningBalance.DoesNotExist:
        return JsonResponse({'error': 'Balance not found'}, status=404)
    

# Category-------------------------------------------------------------------------------------------------------------------------------------------
@login_required
@staff_member_required
def viewCategory(request):
    
    categories = Category.objects.all()
    category_exists = categories.exists()
    category_form = CategoryForm()
    context = {'categories': categories, 'category_exists': category_exists, 'category_form': category_form}
    return render(request, 'category.html', context)

@login_required
@staff_member_required
def createCategory(request):
    
    print("in url")
    
    if request.method == 'POST':
        
        print("in post")
        
        category_form = CategoryForm(request.POST)
        if category_form.is_valid():
            print("in valid")
            
            category_form.save()
            return redirect('pettycash_app:category')

@login_required
@staff_member_required
def updateCategory(request, id):
    
    category = get_object_or_404(Category, pk=id)
    category_form = CategoryForm(instance=category)
    if request.method == 'POST':
        
        category_form = CategoryForm(request.POST, instance=category)
        if category_form.is_valid():
            
            category_form.save()
            return redirect('pettycash_app:category')
            
@login_required
@staff_member_required
def deleteCategory(request, id):
    
    category = get_object_or_404(Category, pk=id)
    category.delete()
    return redirect('pettycash_app:category')


# PettyCash-------------------------------------------------------------------------------------------------------------------------------------------
@login_required
def viewPettyCash(request):
    
    pettycashes = PettyCash.objects.all().order_by('-voucher_code')
    pettycash_exists = pettycashes.exists()
    context = {'pettycashes': pettycashes, 'pettycash_exists': pettycash_exists}
    return render(request, 'pettycash/view_pettycash.html', context)

@login_required
def createPettyCash(request):
    
    pettycash_form = PettyCashForm()
    if request.method == 'POST':
        
        pettycash_form = PettyCashForm(request.POST)
        
        # Generating Voucher Code
        voucher_codes_only = VoucherCodeStore.objects.all().values_list('voucher_code', flat=True)
        
        voucher_code_loop = True
        voucher_code_number = 1001
        
        while voucher_code_loop:
            
            generated_voucher_code = "VC_" + str(voucher_code_number)

            if generated_voucher_code in voucher_codes_only:
                voucher_code_number += 1
            else:
                break
                
        if pettycash_form.is_valid():
            
            pettycash = pettycash_form.save(commit=False)
            pettycash.voucher_code = generated_voucher_code
            VoucherCodeStore.objects.create(voucher_code=generated_voucher_code)
            pettycash.save()
            return redirect('pettycash_app:view_pettycash')
            
    context = {'pettycash_form': pettycash_form}
    return render(request, 'pettycash/pettycash.html', context)

@login_required
@staff_member_required
def updatePettyCash(request, id):
    
    pettycash = get_object_or_404(PettyCash, pk=id)
    voucher_code_stored =  pettycash.voucher_code
    pettycash_form = PettyCashForm(instance=pettycash)
    if request.method == 'POST':
        
        pettycash_form = PettyCashForm(request.POST, instance=pettycash)
        if pettycash_form.is_valid():
            pettycash = pettycash_form.save(commit=False)
            pettycash.voucher_code = voucher_code_stored
            pettycash.save()
            return redirect(reverse('pettycash_app:each_pettycash', kwargs={'id': pettycash.id}))
            
    context = {'pettycash_form': pettycash_form, 'pettycash': pettycash}
    return render(request, 'pettycash/pettycash.html', context)

@login_required
def eachPettyCash(request, id):
    
    pettycash = get_object_or_404(PettyCash, pk=id)
    context = {'pettycash': pettycash}
    return render(request, 'pettycash/each_pettycash.html', context)

@login_required
@staff_member_required
def pettyCashSignature(request):
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        image_data = request.POST.get('image_data')

        print('pettycash', image_data)
    
        if image_data:
            # Decode base64 image data
            format, imgstr = image_data.split(';base64,')
            ext = format.split('/')[-1]
            image_data = ContentFile(base64.b64decode(imgstr), name='temp.' + ext)

project_pettycash/pettycash_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Tailwind CSS from CDN -->
        <script src="https://cdn.tailwindcss.com"></script>

        <!-- Flowbite -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />

        <!-- JQUERY CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        <!-- Include SignaturePad library -->
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jSignature/2.1.2/jSignature.min.js"></script>


        {% block head %}{% endblock head %}

    </head>
    <body id="pageBodyView" class="bg-zinc-300 scroll-smooth">
        
        <!-- NAVBAR -->
        <nav class="fixed top-0 z-50 w-full border-b bg-gray-800 border-gray-700">
            <div class="flex items-center justify-between text-white font-bold p-2 px-4">
                <div>
                    <a href="{% url "pettycash_app:choose_cashbook" %}" class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                            <path fill-rule="evenodd" d="M9.293 2.293a1 1 0 0 1 1.414 0l7 7A1 1 0 0 1 17 11h-1v6a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-6H3a1 1 0 0 1-.707-1.707l7-7Z" clip-rule="evenodd" />
                        </svg>                        
                    </a>
                </div>

                <div class="flex items-center gap-x-3">
                    <span class="font-medium uppercase">{{request.user}}</span>
                    <a href="/auth/logout/">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                            <path fill-rule="evenodd" d="M16.5 3.75a1.5 1.5 0 0 1 1.5 1.5v13.5a1.5 1.5 0 0 1-1.5 1.5h-6a1.5 1.5 0 0 1-1.5-1.5V15a.75.75 0 0 0-1.5 0v3.75a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V5.25a3 3 0 0 0-3-3h-6a3 3 0 0 0-3 3V9A.75.75 0 1 0 9 9V5.25a1.5 1.5 0 0 1 1.5-1.5h6ZM5.78 8.47a.75.75 0 0 0-1.06 0l-3 3a.75.75 0 0 0 0 1.06l3 3a.75.75 0 0 0 1.06-1.06l-1.72-1.72H15a.75.75 0 0 0 0-1.5H4.06l1.72-1.72a.75.75 0 0 0 0-1.06Z" clip-rule="evenodd" />
                        </svg>            
                    </a>          
                </div>
            </div>
        </nav>

        <div class="mt-10 px-4 py-2">
            {% block content %}{% endblock content %}
        </div>

        <!-- Flowbite -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>

    </body>
</html>

project_pettycash/pettycash_app/templates/main.html
{% extends 'index.html' %}

{% block head %}
    <title>Menu</title>
{% endblock head %}

{% block content %}

    <div class="grid gap-20 w-full justify-center text-center mt-12">

        <div>
            <span class="font-bold text-4xl ">Menu</span>
        </div>

        {% if request.user.is_staff %}
        <div>
            <a href="{% url "pettycash_app:view_opening_balance" %}" class="bg-blue-600 text-white rounded-lg p-6 hover:bg-blue-900">Opening Balance</a>
        </div>
        {% endif %}

        <div>
            <a href="{% url "pettycash_app:view_pettycash" %}" class="bg-blue-600 text-white rounded-lg p-6 hover:bg-blue-900">Petty Cash</a>
        </div>

        <div>
            <a href="{% url "pettycash_app:view_federal_pettycash" %}" class="bg-blue-600 text-white rounded-lg p-6 hover:bg-blue-900">Federal Bank</a>
        </div>

        <div>
            <a href="{% url "pettycash_app:view_sbi_pettycash" %}" class="bg-blue-600 text-white rounded-lg p-6 hover:bg-blue-900">SBI Bank</a>
        </div>
        
    </div>

{% endblock content %}